@startwbs
'https://plantuml.com/wbs-diagram

* 旅游自助系统
** 交通
*** 导航
*** 网约车
*** 订票
**** 火车票
**** 飞机票
** 美食
*** 地点
**** 路线导航
**** 网约车
**** ……
*** 价格
*** 评论
** 购物
*** 地点
**** 路线导航
**** 网约车
**** ……
*** 特产
*** 评论
** 景点
*** 地点
**** 路线导航
**** 网约车
**** ……
*** 攻略
**** 玩法
**** 打卡点
**** ……
*** 天气
*** 门票
*** 评论
** 住宿
*** 地点
**** 导航
***** 周边美食
***** 周边景点
**** 网约车
**** ……
*** 预约
*** 评论
** 我的
*** 我的会员
**** 网约车排队优先级
**** 回忆录相册容量扩容
**** 代币兑换会员代金券
**** AI助手询问优先级提升
*** AI助手
**** 新建对话
**** 历史对话
*** 我的信息
**** 头像
**** 用户名
**** 手机号
**** 绑定微信
**** 住宿信息
***** 姓名
***** 电话
***** 身份证
*** 我的关注
*** 我的收藏
*** 我的创作
**** 文章
**** 评论
**** 代币数量（兑换代金券，通过发布内容获取）
*** 我的足迹
**** 打卡地图
***** 点击地图中的打卡点可跳转回忆录
**** 回忆录
***** 相册
****** 相册和相册内图片的CRUD
****** 相册权限
******* 私有的
******* 指定多个用户
******* 公开的
**** 回忆录扩容收费

@endwbs