@startwbs
'https://plantuml.com/wbs-diagram

* 旅游自助系统
** 美食
*** 地点
**** 路线导航
**** 网约车
**** ……
*** 价格
*** 评论
** 购物
*** 地点
**** 路线导航
**** 网约车
**** ……
*** 特产
*** 评论
** 景点
*** 地点
**** 路线导航
**** 网约车
**** ……
*** 攻略
**** 玩法
**** 打卡点
**** ……
*** 天气
*** 门票
*** 评论
** 交通
*** 导航
*** 网约车
*** 订票
**** 火车票
**** 飞机票
** 住宿
*** 地点
**** 导航
***** 周边美食
***** 周边景点
**** 网约车
**** ……
*** 预约
*** 评论

@endwbs